AICP: {
  Registration: {
    type: "Pointmatcher", # GICP, Kaess
    sensorRange: 30.0,         # in meters
    sensorAngularView: 270.0,  # in degrees
    loadPosesFrom: "pcd",

    Pointmatcher: {
      configFileName: "/home/snobili/code/aicp_base/git/aicp/aicp_core/config/icp/icp_autotuned_default.yaml",
    }
  },
  Overlap: {
    type: "OctreeBased",

    OctreeBased: {
      octomapResolution: 0.2,
    }
  },
  Classifier: {
    type: "SVM",

    SVM: {
      threshold: 0.50,
      trainingFile: "${DRS_BASE}/../aicp/data/labels/training_all_labelled_1Sep.txt",
      testingFile: "${DRS_BASE}/../aicp/data/labels/testing_labelled_27Aug.txt",
      saveFile: "${DRS_BASE}/../aicp/data/classification/svm_1000training_thresh50_cross_validation_opencv3.xml",
      saveProbs: "${DRS_BASE}/../aicp/data/classification/probs_test.txt",
      modelLocation: "${DRS_BASE}/../aicp/data/models/svm_opencv3.xml",
    },
  },
}
