AICP: {
  Registration: {
    type: "Pointmatcher", # GICP, Kaess
    loadPosesFromFile: "pose_scanner_leica_affine.txt", # Ground truth poses
    saveCorrectedPose: true, # Valid if loadPosesFromFile, otherwise saves init + transform
    saveInitializedReadingCloud: true,
    saveRegisteredReadingCloud: true,
    enableLcmVisualization: true,

    Pointmatcher: {
      configFileName: "icp_autotuned_default.yaml", # points
      initialTransform: "0.1,0.1,0.1", # x[m], y[m], yaw[deg]
      printOutputStatistics: false,
    }
  }
}
